name: Python CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'python/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python: [3.9, 3.13 ]
        splunk-version:
          - "8.0"
          - "latest"
      fail-fast: false

    services:
      splunk:
        image: splunk/splunk:${{matrix.splunk-version}}
        env:
          SPLUNK_START_ARGS: --accept-license
          SPLUNK_HEC_TOKEN: 11111111-1111-1111-1111-1111111111113
          SPLUNK_PASSWORD: changed!
          SPLUNK_APPS_URL: https://github.com/splunk/sdk-app-collection/releases/download/v1.1.0/sdkappcollection.tgz
        ports:
          - 8000:8000
          - 8088:8088
          - 8089:8089

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        working-directory: ./python
        run: pip install tox
      - name: Install splunk-sdk
        working-directory: ./python
        run: pip install splunk-sdk
      - name: Test Execution
        working-directory: ./python
        run: tox -e py
